### ISSUE TITLE
Shortcut to show all available patterns

### ISSUE THREAD

**Issue by tienthanh8490** [caiogondim/js-patterns-sublime-snippets#28]
Hi, would it be possible to show all available patterns (as a dropdown list maybe) using a shortcut ? I'm a new user and I find it more convenient than remembering all patterns' abbreviations. Thanks for the useful plugin by the way.

**Comment by caiogondim** [comment]
If you do `shift` + `cmd` + `P` and type `pattern` you can see the snippets.
![screen shot 2016-05-17 at 20 55 24](https://cloud.githubusercontent.com/assets/33044/15335267/e5a462ca-1c71-11e6-916c-0552c644e71c.png)
