### ISSUE TITLE
Once Pattern Doesn't Work By Default

### ISSUE THREAD

**Issue by steveosoule** [caiogondim/js-patterns-sublime-snippets#30]
Using the Once pattern will put your cursor at the two `functionName`'s and allow you to change them, but when execute your function, you will get an `Uncaught ReferenceError: foo is not defined` error.

Seems like if you replace:
```
return foo.apply(this, arguments);
```
with

```
return ${1:functionName}.apply(this, arguments);
```
then it will fix it.

**Comment by caiogondim** [comment]
Fixed on 25da6ef1efbdccc20a7a8fac3cd5b9894f1dab7f
Thanks a lot.
